// Shared domain types for Grievance AI.

export type Role = "citizen" | "admin";

export type Category =
  | "Water"
  | "Roads"
  | "Electricity"
  | "Sanitation"
  | "Safety"
  | "Other";

export type Priority = "Low" | "Medium" | "High" | "Urgent";

export type Status = "Pending" | "In Progress" | "Resolved";

export type GrievanceLanguage = "English" | "Hindi" | "Marathi";

export interface PublicUser {
  id: string;
  name: string;
  email: string;
  role: Role;
  createdAt: string;
}

export interface SessionPayload {
  userId: string;
  email: string;
  name: string;
  role: Role;
}

export interface GrievanceAnalysis {
  detectedLanguage: GrievanceLanguage;
  category: Category;
  priority: Priority;
  summary: string;
}

/** A grievance as serialized over the API / stored in the DB. */
export interface Grievance {
  id: string;
  title: string;
  description: string;
  language: GrievanceLanguage;
  category: Category;
  priority: Priority;
  status: Status;
  location: string;
  submittedBy: string;
  submitterName: string;
  createdAt: string;
  updatedAt: string;
  /** Short English summary generated by Gemini. */
  aiSummary: string;
  /** True when Gemini failed and defaults/manual triage were used instead. */
  aiProcessed: boolean;
  /** Comma-separated list of similarity reasons when grouped as a duplicate. */
  duplicateOf?: string[];
}

export interface AuthResponse {
  user: PublicUser;
}

export interface SubmitGrievanceResponse {
  grievance: Grievance;
  /** Similar nearby grievances of the same category, shown on confirmation. */
  similar: Array<{
    id: string;
    title: string;
    location: string;
    createdAt: string;
    /** Why these were flagged as similar. */
    reasons?: string[];
  }>;
}
