// Shared domain types for Grievance AI.

export type Role = "citizen" | "admin";

export type Category =
  | "Water"
  | "Roads"
  | "Electricity"
  | "Sanitation"
  | "Safety"
  | "Other";

export type Priority = "Low" | "Medium" | "High" | "Urgent";

export type Status = "Pending" | "In Progress" | "Resolved";

export type GrievanceLanguage = "English" | "Hindi" | "Marathi";

export interface PublicUser {
  id: string;
  name: string;
  email: string;
  role: Role;
  createdAt: string;
}

export interface SessionPayload {
  userId: string;
  email: string;
  name: string;
  role: Role;
}

/**
 * Estimated time to resolve, produced by Gemini alongside the prose steps so
 * the citizen-facing summary and the officer-facing detail stay in sync.
 */
export type ResolutionTimeframe =
  | "Same day"
  | "24 hours"
  | "2-3 days"
  | "About a week"
  | "Within two weeks";

export interface GrievanceAnalysis {
  detectedLanguage: GrievanceLanguage;
  category: Category;
  priority: Priority;
  summary: string;
  /** Short actionable guidance for the officer: steps, typical fix, timeframe. */
  recommendedResolution: string;
  /** Structured estimate extracted from the same analysis, for the citizen view. */
  resolutionTimeframe: ResolutionTimeframe;
}

/** A grievance as serialized over the API / stored in the DB. */
export interface Grievance {
  id: string;
  title: string;
  description: string;
  language: GrievanceLanguage;
  category: Category;
  priority: Priority;
  status: Status;
  location: string;
  submittedBy: string;
  submitterName: string;
  createdAt: string;
  updatedAt: string;
  /** Short English summary generated by Gemini. */
  aiSummary: string;
  /**
   * AI-recommended resolution steps for the handling officer (actions, the
   * typical fix for this type of issue, and an estimated timeframe).
   * Empty for records created before this field existed.
   */
  recommendedResolution: string;
  /**
   * Short estimate (e.g. "2-3 days") shown to citizens. Derived from the same
   * AI analysis as `recommendedResolution` — never a separate lookup.
   */
  resolutionTimeframe: ResolutionTimeframe;
  /** True when Gemini failed and defaults/manual triage were used instead. */
  aiProcessed: boolean;
  /** Comma-separated list of similarity reasons when grouped as a duplicate. */
  duplicateOf?: string[];
}

/**
 * Public tracking view of a grievance: everything needed to follow status,
 * without the full description or the submitter's identity.
 */
export interface PublicGrievance {
  id: string;
  title: string;
  language: GrievanceLanguage;
  category: Category;
  priority: Priority;
  status: Status;
  location: string;
  createdAt: string;
  updatedAt: string;
  aiSummary: string;
  /** Officer-facing resolution prose (rendered only for admins). */
  recommendedResolution: string;
  /** Citizen-facing estimate drawn from the same analysis. */
  resolutionTimeframe: ResolutionTimeframe;
  aiProcessed: boolean;
}

/** Response for GET /api/grievances/[id]. */
export interface TrackGrievanceResponse {
  grievance: Grievance | PublicGrievance;
  /** "full" when the requester owns the grievance or is an officer. */
  visibility: "full" | "public";
}

export interface AuthResponse {
  user: PublicUser;
}

export interface SubmitGrievanceResponse {
  grievance: Grievance;
  /** Similar nearby grievances of the same category, shown on confirmation. */
  similar: Array<{
    id: string;
    title: string;
    location: string;
    createdAt: string;
    /** Why these were flagged as similar. */
    reasons?: string[];
  }>;
}
